set_property IOSTANDARD LVCMOS18 [get_ports s0]
set_property IOSTANDARD LVCMOS18 [get_ports s1]
set_property IOSTANDARD LVCMOS18 [get_ports s2]
set_property IOSTANDARD LVCMOS18 [get_ports s3]
set_property IOSTANDARD LVCMOS18 [get_ports y0]
set_property IOSTANDARD LVCMOS18 [get_ports y1]
set_property IOSTANDARD LVCMOS18 [get_ports y2]
set_property IOSTANDARD LVCMOS18 [get_ports y3]
set_property IOSTANDARD LVCMOS18 [get_ports y4]
set_property IOSTANDARD LVCMOS18 [get_ports y5]
set_property IOSTANDARD LVCMOS18 [get_ports y6]
set_property IOSTANDARD LVCMOS18 [get_ports y7]
set_property IOSTANDARD LVCMOS18 [get_ports y8]
set_property IOSTANDARD LVCMOS18 [get_ports y9]
set_property IOSTANDARD LVCMOS18 [get_ports y10]
set_property IOSTANDARD LVCMOS18 [get_ports y11]
set_property IOSTANDARD LVCMOS18 [get_ports y12]
set_property IOSTANDARD LVCMOS18 [get_ports y13]
set_property IOSTANDARD LVCMOS18 [get_ports y14]
set_property IOSTANDARD LVCMOS18 [get_ports y15]
set_property PACKAGE_PIN J4 [get_ports s0]
set_property PACKAGE_PIN L3 [get_ports s1]
set_property PACKAGE_PIN K3 [get_ports s2]
set_property PACKAGE_PIN M2 [get_ports s3]
set_property PACKAGE_PIN F15 [get_ports y0]
set_property PACKAGE_PIN F13 [get_ports y1]
set_property PACKAGE_PIN F14 [get_ports y2]
set_property PACKAGE_PIN F16 [get_ports y3]
set_property PACKAGE_PIN E17 [get_ports y4]
set_property PACKAGE_PIN C14 [get_ports y5]
set_property PACKAGE_PIN C15 [get_ports y6]
set_property PACKAGE_PIN E13 [get_ports y7]
set_property PACKAGE_PIN AA10 [get_ports y8]
set_property PACKAGE_PIN AA11 [get_ports y9]
set_property PACKAGE_PIN V10 [get_ports y10]
set_property PACKAGE_PIN W10 [get_ports y11]
set_property PACKAGE_PIN Y11 [get_ports y12]
set_property PACKAGE_PIN Y!2 [get_ports y13]
set_property PACKAGE_PIN W11 [get_ports y14]
set_property PACKAGE_PIN W12 [get_ports y15]




