set_property IOSTANDARD LVCMOS18 [get_ports s0]
set_property IOSTANDARD LVCMOS18 [get_ports s1]
set_property IOSTANDARD LVCMOS18 [get_ports s2]
set_property IOSTANDARD LVCMOS18 [get_ports d0]
set_property IOSTANDARD LVCMOS18 [get_ports d1]
set_property IOSTANDARD LVCMOS18 [get_ports d2]
set_property IOSTANDARD LVCMOS18 [get_ports d3]
set_property IOSTANDARD LVCMOS18 [get_ports d4]
set_property IOSTANDARD LVCMOS18 [get_ports d5]
set_property IOSTANDARD LVCMOS18 [get_ports d6]
set_property IOSTANDARD LVCMOS18 [get_ports d7]
set_property IOSTANDARD LVCMOS18 [get_ports y]
set_property PACKAGE_PIN J4 [get_ports s0]
set_property PACKAGE_PIN L3 [get_ports s1]
set_property PACKAGE_PIN K3 [get_ports s2]
set_property PACKAGE_PIN M2 [get_ports d0]
set_property PACKAGE_PIN K6 [get_ports d1]
set_property PACKAGE_PIN J6 [get_ports d2]
set_property PACKAGE_PIN L5 [get_ports d3]
set_property PACKAGE_PIN L4 [get_ports d4]
set_property PACKAGE_PIN Y16 [get_ports d5]
set_property PACKAGE_PIN AA16 [get_ports d6]
set_property PACKAGE_PIN AB16 [get_ports d7]
set_property PACKAGE_PIN F15 [get_ports y]


