set_property IOSTANDARD LVCMOS18 [get_ports a[0]]
set_property IOSTANDARD LVCMOS18 [get_ports a[1]]
set_property IOSTANDARD LVCMOS18 [get_ports a[2]]
set_property IOSTANDARD LVCMOS18 [get_ports a[3]]
set_property IOSTANDARD LVCMOS18 [get_ports b[0]]
set_property IOSTANDARD LVCMOS18 [get_ports b[1]]
set_property IOSTANDARD LVCMOS18 [get_ports b[2]]
set_property IOSTANDARD LVCMOS18 [get_ports b[3]]
set_property IOSTANDARD LVCMOS18 [get_ports bin]
set_property IOSTANDARD LVCMOS18 [get_ports D[0]]
set_property IOSTANDARD LVCMOS18 [get_ports D[1]]
set_property IOSTANDARD LVCMOS18 [get_ports D[2]]
set_property IOSTANDARD LVCMOS18 [get_ports D[3]]
set_property IOSTANDARD LVCMOS18 [get_ports bout]
set_property PACKAGE_PIN J4 [get_ports a[0]]
set_property PACKAGE_PIN L3 [get_ports a[1]]
set_property PACKAGE_PIN K3 [get_ports a[2]]
set_property PACKAGE_PIN M2 [get_ports a[3]]
set_property PACKAGE_PIN K6 [get_ports b[0]]
set_property PACKAGE_PIN J6 [get_ports b[1]]
set_property PACKAGE_PIN L5 [get_ports b[2]]
set_property PACKAGE_PIN L4 [get_ports b[3]]
set_property PACKAGE_PIN Y16 [get_ports bin]
set_property PACKAGE_PIN F15 [get_ports D[0]]
set_property PACKAGE_PIN F13 [get_ports D[1]]
set_property PACKAGE_PIN F14 [get_ports D[2]]
set_property PACKAGE_PIN F16 [get_ports D[3]]
set_property PACKAGE_PIN E17 [get_ports bout]



